/// File generated by assets.py - Manual changes will probably be overwritten.
const SDL_Texture = @import("sdl2").SDL_Texture;
const StaticMap = @import("utils.zig").StaticMap;

pub const Texture = struct {
    ptr: *SDL_Texture,
    width: usize,
    height: usize,
};

pub const TextureMap = @TypeOf(StaticMap(ID.size(), []Texture, ID));

pub const Asset = struct {
    path: []const u8,
    id: ID,
};

pub const ID = enum(u16) {
    CHARACTER_TEST_FLY,
    CHARACTER_GUY_STAND,
    CHARACTER_ALIEN_STAND,
    __LAST__,

    inline fn size() u16 {
        return @intFromEnum(ID.__LAST__);
    }
};

pub fn IDFromEntityMode(mode: EntityMode) ID {
    switch (mode) {
        .character_test => |character_test_mode| switch (character_test_mode) {
            .FLY => return ID.CHARACTER_TEST_FLY,
        },
        .character_guy => |character_guy_mode| switch (character_guy_mode) {
            .STAND => return ID.CHARACTER_GUY_STAND,
        },
        .character_alien => |character_alien_mode| switch (character_alien_mode) {
            .STAND => return ID.CHARACTER_ALIEN_STAND,
        },
    }
    unreachable; // shouldn't happen
}

pub const EntityMode = union(enum(u16)) {
    character_test: CharacterTestMode,
    character_guy: CharacterGuyMode,
    character_alien: CharacterAlienMode,
};

const CharacterTestMode = enum(u16) {
    FLY,
};

const CharacterGuyMode = enum(u16) {
    STAND,
};

const CharacterAlienMode = enum(u16) {
    STAND,
};

pub const ALL: [19]Asset = .{
    .{ .path = "assets/Character/Test/Fly/3.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/8.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/6.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/10.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/17.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/7.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/4.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/15.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/5.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/13.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/14.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/16.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/1.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/11.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/12.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/2.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Test/Fly/9.png", .id = .CHARACTER_TEST_FLY },
    .{ .path = "assets/Character/Guy/Stand/first_guy_big.png", .id = .CHARACTER_GUY_STAND },
    .{ .path = "assets/Character/Alien/Stand/body.png", .id = .CHARACTER_ALIEN_STAND },
};

pub const ASSETS_PER_ID: [ID.size()]usize = .{ 17, 1, 1 };
