/// File generated by audio_assets.py - Manual changes will probably be overwritten.
const StaticMap = @import("utils.zig").StaticMap;
const fields = @import("std").meta.fields;
const print = @import("std").debug.print;

pub const WavFile = struct {
    start_ptr: ?*u8,
    length: u32,
};

pub const AudioAsset = struct {
    path: [:0]const u8,
    id: ID,
};

pub const ID = enum(u16) {
    MENU_MUSIC_TRACK1,

    pub inline fn int(comptime id: ID) u16 {
        return @intFromEnum(id);
    }

    pub inline fn size() u16 {
        return fields(ID).len;
    }
};

pub const ALL: [1]AudioAsset = .{
    .{ .path = "assets/audio/Menu/Music/Track1/1.wav", .id = .MENU_MUSIC_TRACK1 },
};

pub const ASSETS_PER_ID: [ID.size()]usize = .{ 1 };

// Storage for .wav files to be initialized at runtime.
var menu_music_track1_wavfiles: [1]WavFile = undefined;

pub var wavfile_slices: [ID.size()][]WavFile = .{
    &menu_music_track1_wavfiles,
};
