/// File generated by visual_assets.py - Manual changes will probably be overwritten.
/// Stage parts are also separated into 'Modes', which doesn't really make sense,
/// but I don't feel like having separate logic for stages.
const SDL_Texture = @import("sdl2").SDL_Texture;
const StaticMap = @import("utils.zig").StaticMap;
const fields = @import("std").meta.fields;
const print = @import("std").debug.print;

pub const Texture = struct {
    ptr: ?*SDL_Texture,
    width: c_int,
    height: c_int,
};

pub const Asset = struct {
    path: []const u8,
    id: ID,
};

pub const ID = enum(u16) {
    CHARACTER_TEST_FLYING_RIGHT,
    CHARACTER_TEST_STANDING,
    CHARACTER_TEST_ATTACKING_LEFT,
    CHARACTER_TEST_FLYING_LEFT,
    CHARACTER_TEST_RUNNING_RIGHT,
    CHARACTER_TEST_ATTACKING_RIGHT,
    CHARACTER_TEST_RUNNING_LEFT,
    CHARACTER_TEST_ATTACKING_DOWN,
    CHARACTER_TEST_ATTACKING_UP,
    CHARACTER_TEST_FLYING_NEUTRAL,
    CHARACTER_TEST_JUMPING,
    CHARACTER_WURMPLE_FLYING_RIGHT,
    CHARACTER_WURMPLE_STANDING,
    CHARACTER_WURMPLE_ATTACKING_LEFT,
    CHARACTER_WURMPLE_FLYING_LEFT,
    CHARACTER_WURMPLE_RUNNING_RIGHT,
    CHARACTER_WURMPLE_ATTACKING_RIGHT,
    CHARACTER_WURMPLE_RUNNING_LEFT,
    CHARACTER_WURMPLE_ATTACKING_DOWN,
    CHARACTER_WURMPLE_ATTACKING_UP,
    CHARACTER_WURMPLE_FLYING_NEUTRAL,
    CHARACTER_WURMPLE_JUMPING,
    DONT_LOAD_TEXTURE,
    PROJECTILE_TEST_FLYING_DOWN,
    PROJECTILE_TEST_FLYING_RIGHT,
    PROJECTILE_TEST_FLYING_LEFT,
    PROJECTILE_TEST_FLYING_UP,
    UI_AMMO_EQUALS4,
    UI_AMMO_EQUALS1,
    UI_AMMO_EQUALS7,
    UI_AMMO_EQUALS2,
    UI_AMMO_EQUALS6,
    UI_AMMO_EQUALS0,
    UI_AMMO_EQUALS3,
    UI_AMMO_EQUALS5,
    UI_PLAYER_NOTPLAYING,
    UI_PLAYER_PLAYING,
    UI_HEALTH_EQUALS4,
    UI_HEALTH_EQUALS11,
    UI_HEALTH_EQUALS1,
    UI_HEALTH_EQUALS15,
    UI_HEALTH_EQUALS8,
    UI_HEALTH_EQUALS14,
    UI_HEALTH_EQUALS12,
    UI_HEALTH_EQUALS7,
    UI_HEALTH_EQUALS2,
    UI_HEALTH_EQUALS6,
    UI_HEALTH_EQUALS9,
    UI_HEALTH_EQUALS10,
    UI_HEALTH_EQUALS0,
    UI_HEALTH_EQUALS13,
    UI_HEALTH_EQUALS3,
    UI_HEALTH_EQUALS5,
    UI_PAUSED_BACKGROUND,
    STAGE_METEOR_BACKGROUND,
    STAGE_METEOR_THUMBNAIL,
    STAGE_METEOR_PLATFORMS,
    STAGE_METEOR_FLOOR,
    STAGE_TEST00_BACKGROUND,
    STAGE_TEST00_THUMBNAIL,
    STAGE_TEST00_PLATFORMS,
    MENU_WAITING_FORINPUT,
    MENU_STAGE_SELECTED,

    pub inline fn int(id: ID) u16 {
        return @intFromEnum(id);
    }

    pub inline fn size() u16 {
        return fields(ID).len;
    }
};

pub fn IDFromEntityMode(mode: EntityMode) ID {
    switch (mode) {
        .character_test => |character_test_mode| switch (character_test_mode) {
            .FLYING_RIGHT => return ID.CHARACTER_TEST_FLYING_RIGHT,
            .STANDING => return ID.CHARACTER_TEST_STANDING,
            .ATTACKING_LEFT => return ID.CHARACTER_TEST_ATTACKING_LEFT,
            .FLYING_LEFT => return ID.CHARACTER_TEST_FLYING_LEFT,
            .RUNNING_RIGHT => return ID.CHARACTER_TEST_RUNNING_RIGHT,
            .ATTACKING_RIGHT => return ID.CHARACTER_TEST_ATTACKING_RIGHT,
            .RUNNING_LEFT => return ID.CHARACTER_TEST_RUNNING_LEFT,
            .ATTACKING_DOWN => return ID.CHARACTER_TEST_ATTACKING_DOWN,
            .ATTACKING_UP => return ID.CHARACTER_TEST_ATTACKING_UP,
            .FLYING_NEUTRAL => return ID.CHARACTER_TEST_FLYING_NEUTRAL,
            .JUMPING => return ID.CHARACTER_TEST_JUMPING,
        },
        .character_wurmple => |character_wurmple_mode| switch (character_wurmple_mode) {
            .FLYING_RIGHT => return ID.CHARACTER_WURMPLE_FLYING_RIGHT,
            .STANDING => return ID.CHARACTER_WURMPLE_STANDING,
            .ATTACKING_LEFT => return ID.CHARACTER_WURMPLE_ATTACKING_LEFT,
            .FLYING_LEFT => return ID.CHARACTER_WURMPLE_FLYING_LEFT,
            .RUNNING_RIGHT => return ID.CHARACTER_WURMPLE_RUNNING_RIGHT,
            .ATTACKING_RIGHT => return ID.CHARACTER_WURMPLE_ATTACKING_RIGHT,
            .RUNNING_LEFT => return ID.CHARACTER_WURMPLE_RUNNING_LEFT,
            .ATTACKING_DOWN => return ID.CHARACTER_WURMPLE_ATTACKING_DOWN,
            .ATTACKING_UP => return ID.CHARACTER_WURMPLE_ATTACKING_UP,
            .FLYING_NEUTRAL => return ID.CHARACTER_WURMPLE_FLYING_NEUTRAL,
            .JUMPING => return ID.CHARACTER_WURMPLE_JUMPING,
        },
        .dont_load => |dont_load_mode| switch (dont_load_mode) {
            .TEXTURE => return ID.DONT_LOAD_TEXTURE,
        },
        .projectile_test => |projectile_test_mode| switch (projectile_test_mode) {
            .FLYING_DOWN => return ID.PROJECTILE_TEST_FLYING_DOWN,
            .FLYING_RIGHT => return ID.PROJECTILE_TEST_FLYING_RIGHT,
            .FLYING_LEFT => return ID.PROJECTILE_TEST_FLYING_LEFT,
            .FLYING_UP => return ID.PROJECTILE_TEST_FLYING_UP,
        },
        .ui_ammo => |ui_ammo_mode| switch (ui_ammo_mode) {
            .EQUALS4 => return ID.UI_AMMO_EQUALS4,
            .EQUALS1 => return ID.UI_AMMO_EQUALS1,
            .EQUALS7 => return ID.UI_AMMO_EQUALS7,
            .EQUALS2 => return ID.UI_AMMO_EQUALS2,
            .EQUALS6 => return ID.UI_AMMO_EQUALS6,
            .EQUALS0 => return ID.UI_AMMO_EQUALS0,
            .EQUALS3 => return ID.UI_AMMO_EQUALS3,
            .EQUALS5 => return ID.UI_AMMO_EQUALS5,
        },
        .ui_player => |ui_player_mode| switch (ui_player_mode) {
            .NOTPLAYING => return ID.UI_PLAYER_NOTPLAYING,
            .PLAYING => return ID.UI_PLAYER_PLAYING,
        },
        .ui_health => |ui_health_mode| switch (ui_health_mode) {
            .EQUALS4 => return ID.UI_HEALTH_EQUALS4,
            .EQUALS11 => return ID.UI_HEALTH_EQUALS11,
            .EQUALS1 => return ID.UI_HEALTH_EQUALS1,
            .EQUALS15 => return ID.UI_HEALTH_EQUALS15,
            .EQUALS8 => return ID.UI_HEALTH_EQUALS8,
            .EQUALS14 => return ID.UI_HEALTH_EQUALS14,
            .EQUALS12 => return ID.UI_HEALTH_EQUALS12,
            .EQUALS7 => return ID.UI_HEALTH_EQUALS7,
            .EQUALS2 => return ID.UI_HEALTH_EQUALS2,
            .EQUALS6 => return ID.UI_HEALTH_EQUALS6,
            .EQUALS9 => return ID.UI_HEALTH_EQUALS9,
            .EQUALS10 => return ID.UI_HEALTH_EQUALS10,
            .EQUALS0 => return ID.UI_HEALTH_EQUALS0,
            .EQUALS13 => return ID.UI_HEALTH_EQUALS13,
            .EQUALS3 => return ID.UI_HEALTH_EQUALS3,
            .EQUALS5 => return ID.UI_HEALTH_EQUALS5,
        },
        .ui_paused => |ui_paused_mode| switch (ui_paused_mode) {
            .BACKGROUND => return ID.UI_PAUSED_BACKGROUND,
        },
        .stage_meteor => |stage_meteor_mode| switch (stage_meteor_mode) {
            .BACKGROUND => return ID.STAGE_METEOR_BACKGROUND,
            .THUMBNAIL => return ID.STAGE_METEOR_THUMBNAIL,
            .PLATFORMS => return ID.STAGE_METEOR_PLATFORMS,
            .FLOOR => return ID.STAGE_METEOR_FLOOR,
        },
        .stage_test00 => |stage_test00_mode| switch (stage_test00_mode) {
            .BACKGROUND => return ID.STAGE_TEST00_BACKGROUND,
            .THUMBNAIL => return ID.STAGE_TEST00_THUMBNAIL,
            .PLATFORMS => return ID.STAGE_TEST00_PLATFORMS,
        },
        .menu_waiting => |menu_waiting_mode| switch (menu_waiting_mode) {
            .FORINPUT => return ID.MENU_WAITING_FORINPUT,
        },
        .menu_stage => |menu_stage_mode| switch (menu_stage_mode) {
            .SELECTED => return ID.MENU_STAGE_SELECTED,
        },
    }
    unreachable; // shouldn't happen
}

pub const EntityMode = union(enum(u16)) {
    character_test: CharacterTestMode,
    character_wurmple: CharacterWurmpleMode,
    dont_load: DontLoadMode,
    projectile_test: ProjectileTestMode,
    ui_ammo: UiAmmoMode,
    ui_player: UiPlayerMode,
    ui_health: UiHealthMode,
    ui_paused: UiPausedMode,
    stage_meteor: StageMeteorMode,
    stage_test00: StageTest00Mode,
    menu_waiting: MenuWaitingMode,
    menu_stage: MenuStageMode,

    pub fn from_enum_literal(comptime Type: type, comptime val: @TypeOf(.enum_literal)) @This() {
        switch (Type) {
            CharacterTestMode => |Enum| return @unionInit(@This(), "character_test", @as(Enum, val)),
            CharacterWurmpleMode => |Enum| return @unionInit(@This(), "character_wurmple", @as(Enum, val)),
            DontLoadMode => |Enum| return @unionInit(@This(), "dont_load", @as(Enum, val)),
            ProjectileTestMode => |Enum| return @unionInit(@This(), "projectile_test", @as(Enum, val)),
            UiAmmoMode => |Enum| return @unionInit(@This(), "ui_ammo", @as(Enum, val)),
            UiPlayerMode => |Enum| return @unionInit(@This(), "ui_player", @as(Enum, val)),
            UiHealthMode => |Enum| return @unionInit(@This(), "ui_health", @as(Enum, val)),
            UiPausedMode => |Enum| return @unionInit(@This(), "ui_paused", @as(Enum, val)),
            StageMeteorMode => |Enum| return @unionInit(@This(), "stage_meteor", @as(Enum, val)),
            StageTest00Mode => |Enum| return @unionInit(@This(), "stage_test00", @as(Enum, val)),
            MenuWaitingMode => |Enum| return @unionInit(@This(), "menu_waiting", @as(Enum, val)),
            MenuStageMode => |Enum| return @unionInit(@This(), "menu_stage", @as(Enum, val)),

            else => |mode| {
                print("\nUnexpected entity mode: {any}\n", .{mode});
                unreachable; // shouldn't happen
            }
        }
    }
};

pub const CharacterTestMode = enum(u16) {
    FLYING_RIGHT,
    STANDING,
    ATTACKING_LEFT,
    FLYING_LEFT,
    RUNNING_RIGHT,
    ATTACKING_RIGHT,
    RUNNING_LEFT,
    ATTACKING_DOWN,
    ATTACKING_UP,
    FLYING_NEUTRAL,
    JUMPING,
};

pub const CharacterWurmpleMode = enum(u16) {
    FLYING_RIGHT,
    STANDING,
    ATTACKING_LEFT,
    FLYING_LEFT,
    RUNNING_RIGHT,
    ATTACKING_RIGHT,
    RUNNING_LEFT,
    ATTACKING_DOWN,
    ATTACKING_UP,
    FLYING_NEUTRAL,
    JUMPING,
};

pub const DontLoadMode = enum(u16) {
    TEXTURE,
};

pub const ProjectileTestMode = enum(u16) {
    FLYING_DOWN,
    FLYING_RIGHT,
    FLYING_LEFT,
    FLYING_UP,
};

pub const UiAmmoMode = enum(u16) {
    EQUALS4,
    EQUALS1,
    EQUALS7,
    EQUALS2,
    EQUALS6,
    EQUALS0,
    EQUALS3,
    EQUALS5,
};

pub const UiPlayerMode = enum(u16) {
    NOTPLAYING,
    PLAYING,
};

pub const UiHealthMode = enum(u16) {
    EQUALS4,
    EQUALS11,
    EQUALS1,
    EQUALS15,
    EQUALS8,
    EQUALS14,
    EQUALS12,
    EQUALS7,
    EQUALS2,
    EQUALS6,
    EQUALS9,
    EQUALS10,
    EQUALS0,
    EQUALS13,
    EQUALS3,
    EQUALS5,
};

pub const UiPausedMode = enum(u16) {
    BACKGROUND,
};

pub const StageMeteorMode = enum(u16) {
    BACKGROUND,
    THUMBNAIL,
    PLATFORMS,
    FLOOR,
};

pub const StageTest00Mode = enum(u16) {
    BACKGROUND,
    THUMBNAIL,
    PLATFORMS,
};

pub const MenuWaitingMode = enum(u16) {
    FORINPUT,
};

pub const MenuStageMode = enum(u16) {
    SELECTED,
};

pub const ALL: [317]Asset = .{
    .{ .path = "assets/visual/Character/Test/Flying_Right/1.png", .id = .CHARACTER_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Flying_Right/2.png", .id = .CHARACTER_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Flying_Right/3.png", .id = .CHARACTER_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Flying_Right/4.png", .id = .CHARACTER_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Flying_Right/5.png", .id = .CHARACTER_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Standing/1.png", .id = .CHARACTER_TEST_STANDING },
    .{ .path = "assets/visual/Character/Test/Standing/2.png", .id = .CHARACTER_TEST_STANDING },
    .{ .path = "assets/visual/Character/Test/Standing/3.png", .id = .CHARACTER_TEST_STANDING },
    .{ .path = "assets/visual/Character/Test/Standing/4.png", .id = .CHARACTER_TEST_STANDING },
    .{ .path = "assets/visual/Character/Test/Standing/5.png", .id = .CHARACTER_TEST_STANDING },
    .{ .path = "assets/visual/Character/Test/Standing/6.png", .id = .CHARACTER_TEST_STANDING },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/1.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/2.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/3.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/4.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/5.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/6.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/7.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/8.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/9.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/10.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/11.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Left/12.png", .id = .CHARACTER_TEST_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Test/Flying_Left/1.png", .id = .CHARACTER_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Character/Test/Flying_Left/2.png", .id = .CHARACTER_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Character/Test/Flying_Left/3.png", .id = .CHARACTER_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Character/Test/Flying_Left/4.png", .id = .CHARACTER_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Character/Test/Flying_Left/5.png", .id = .CHARACTER_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Character/Test/Running_Right/1.png", .id = .CHARACTER_TEST_RUNNING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Running_Right/2.png", .id = .CHARACTER_TEST_RUNNING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Running_Right/3.png", .id = .CHARACTER_TEST_RUNNING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Running_Right/4.png", .id = .CHARACTER_TEST_RUNNING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Running_Right/5.png", .id = .CHARACTER_TEST_RUNNING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/1.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/2.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/3.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/4.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/5.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/6.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/7.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/8.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/9.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/10.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/11.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Attacking_Right/12.png", .id = .CHARACTER_TEST_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Test/Running_Left/1.png", .id = .CHARACTER_TEST_RUNNING_LEFT },
    .{ .path = "assets/visual/Character/Test/Running_Left/2.png", .id = .CHARACTER_TEST_RUNNING_LEFT },
    .{ .path = "assets/visual/Character/Test/Running_Left/3.png", .id = .CHARACTER_TEST_RUNNING_LEFT },
    .{ .path = "assets/visual/Character/Test/Running_Left/4.png", .id = .CHARACTER_TEST_RUNNING_LEFT },
    .{ .path = "assets/visual/Character/Test/Running_Left/5.png", .id = .CHARACTER_TEST_RUNNING_LEFT },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/1.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/2.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/3.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/4.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/5.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/6.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/7.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/8.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/9.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/10.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/11.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Down/12.png", .id = .CHARACTER_TEST_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/1.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/2.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/3.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/4.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/5.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/6.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/7.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/8.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/9.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/10.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/11.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Attacking_Up/12.png", .id = .CHARACTER_TEST_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Test/Flying_Neutral/1.png", .id = .CHARACTER_TEST_FLYING_NEUTRAL },
    .{ .path = "assets/visual/Character/Test/Flying_Neutral/2.png", .id = .CHARACTER_TEST_FLYING_NEUTRAL },
    .{ .path = "assets/visual/Character/Test/Flying_Neutral/3.png", .id = .CHARACTER_TEST_FLYING_NEUTRAL },
    .{ .path = "assets/visual/Character/Test/Flying_Neutral/4.png", .id = .CHARACTER_TEST_FLYING_NEUTRAL },
    .{ .path = "assets/visual/Character/Test/Flying_Neutral/5.png", .id = .CHARACTER_TEST_FLYING_NEUTRAL },
    .{ .path = "assets/visual/Character/Test/Jumping/1.png", .id = .CHARACTER_TEST_JUMPING },
    .{ .path = "assets/visual/Character/Test/Jumping/2.png", .id = .CHARACTER_TEST_JUMPING },
    .{ .path = "assets/visual/Character/Test/Jumping/3.png", .id = .CHARACTER_TEST_JUMPING },
    .{ .path = "assets/visual/Character/Test/Jumping/4.png", .id = .CHARACTER_TEST_JUMPING },
    .{ .path = "assets/visual/Character/Test/Jumping/5.png", .id = .CHARACTER_TEST_JUMPING },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Right/1.png", .id = .CHARACTER_WURMPLE_FLYING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Right/2.png", .id = .CHARACTER_WURMPLE_FLYING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Right/3.png", .id = .CHARACTER_WURMPLE_FLYING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Right/4.png", .id = .CHARACTER_WURMPLE_FLYING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Right/5.png", .id = .CHARACTER_WURMPLE_FLYING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Standing/1.png", .id = .CHARACTER_WURMPLE_STANDING },
    .{ .path = "assets/visual/Character/Wurmple/Standing/2.png", .id = .CHARACTER_WURMPLE_STANDING },
    .{ .path = "assets/visual/Character/Wurmple/Standing/3.png", .id = .CHARACTER_WURMPLE_STANDING },
    .{ .path = "assets/visual/Character/Wurmple/Standing/4.png", .id = .CHARACTER_WURMPLE_STANDING },
    .{ .path = "assets/visual/Character/Wurmple/Standing/5.png", .id = .CHARACTER_WURMPLE_STANDING },
    .{ .path = "assets/visual/Character/Wurmple/Standing/6.png", .id = .CHARACTER_WURMPLE_STANDING },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/1.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/2.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/3.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/4.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/5.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/6.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/7.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/8.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/9.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/10.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/11.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Left/12.png", .id = .CHARACTER_WURMPLE_ATTACKING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Left/1.png", .id = .CHARACTER_WURMPLE_FLYING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Left/2.png", .id = .CHARACTER_WURMPLE_FLYING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Left/3.png", .id = .CHARACTER_WURMPLE_FLYING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Left/4.png", .id = .CHARACTER_WURMPLE_FLYING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Left/5.png", .id = .CHARACTER_WURMPLE_FLYING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Running_Right/1.png", .id = .CHARACTER_WURMPLE_RUNNING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Running_Right/2.png", .id = .CHARACTER_WURMPLE_RUNNING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Running_Right/3.png", .id = .CHARACTER_WURMPLE_RUNNING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Running_Right/4.png", .id = .CHARACTER_WURMPLE_RUNNING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Running_Right/5.png", .id = .CHARACTER_WURMPLE_RUNNING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/1.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/2.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/3.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/4.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/5.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/6.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/7.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/8.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/9.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/10.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/11.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Right/12.png", .id = .CHARACTER_WURMPLE_ATTACKING_RIGHT },
    .{ .path = "assets/visual/Character/Wurmple/Running_Left/1.png", .id = .CHARACTER_WURMPLE_RUNNING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Running_Left/2.png", .id = .CHARACTER_WURMPLE_RUNNING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Running_Left/3.png", .id = .CHARACTER_WURMPLE_RUNNING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Running_Left/4.png", .id = .CHARACTER_WURMPLE_RUNNING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Running_Left/5.png", .id = .CHARACTER_WURMPLE_RUNNING_LEFT },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/1.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/2.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/3.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/4.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/5.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/6.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/7.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/8.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/9.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/10.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/11.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Down/12.png", .id = .CHARACTER_WURMPLE_ATTACKING_DOWN },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/1.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/2.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/3.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/4.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/5.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/6.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/7.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/8.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/9.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/10.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/11.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Attacking_Up/12.png", .id = .CHARACTER_WURMPLE_ATTACKING_UP },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Neutral/1.png", .id = .CHARACTER_WURMPLE_FLYING_NEUTRAL },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Neutral/2.png", .id = .CHARACTER_WURMPLE_FLYING_NEUTRAL },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Neutral/3.png", .id = .CHARACTER_WURMPLE_FLYING_NEUTRAL },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Neutral/4.png", .id = .CHARACTER_WURMPLE_FLYING_NEUTRAL },
    .{ .path = "assets/visual/Character/Wurmple/Flying_Neutral/5.png", .id = .CHARACTER_WURMPLE_FLYING_NEUTRAL },
    .{ .path = "assets/visual/Character/Wurmple/Jumping/1.png", .id = .CHARACTER_WURMPLE_JUMPING },
    .{ .path = "assets/visual/Character/Wurmple/Jumping/2.png", .id = .CHARACTER_WURMPLE_JUMPING },
    .{ .path = "assets/visual/Character/Wurmple/Jumping/3.png", .id = .CHARACTER_WURMPLE_JUMPING },
    .{ .path = "assets/visual/Character/Wurmple/Jumping/4.png", .id = .CHARACTER_WURMPLE_JUMPING },
    .{ .path = "assets/visual/Character/Wurmple/Jumping/5.png", .id = .CHARACTER_WURMPLE_JUMPING },
    .{ .path = "assets/visual/Dont/Load/Texture/1.png", .id = .DONT_LOAD_TEXTURE },
    .{ .path = "assets/visual/Projectile/Test/Flying_Down/1.png", .id = .PROJECTILE_TEST_FLYING_DOWN },
    .{ .path = "assets/visual/Projectile/Test/Flying_Down/2.png", .id = .PROJECTILE_TEST_FLYING_DOWN },
    .{ .path = "assets/visual/Projectile/Test/Flying_Down/3.png", .id = .PROJECTILE_TEST_FLYING_DOWN },
    .{ .path = "assets/visual/Projectile/Test/Flying_Down/4.png", .id = .PROJECTILE_TEST_FLYING_DOWN },
    .{ .path = "assets/visual/Projectile/Test/Flying_Down/5.png", .id = .PROJECTILE_TEST_FLYING_DOWN },
    .{ .path = "assets/visual/Projectile/Test/Flying_Down/6.png", .id = .PROJECTILE_TEST_FLYING_DOWN },
    .{ .path = "assets/visual/Projectile/Test/Flying_Down/7.png", .id = .PROJECTILE_TEST_FLYING_DOWN },
    .{ .path = "assets/visual/Projectile/Test/Flying_Down/8.png", .id = .PROJECTILE_TEST_FLYING_DOWN },
    .{ .path = "assets/visual/Projectile/Test/Flying_Down/9.png", .id = .PROJECTILE_TEST_FLYING_DOWN },
    .{ .path = "assets/visual/Projectile/Test/Flying_Down/10.png", .id = .PROJECTILE_TEST_FLYING_DOWN },
    .{ .path = "assets/visual/Projectile/Test/Flying_Right/1.png", .id = .PROJECTILE_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Right/2.png", .id = .PROJECTILE_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Right/3.png", .id = .PROJECTILE_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Right/4.png", .id = .PROJECTILE_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Right/5.png", .id = .PROJECTILE_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Right/6.png", .id = .PROJECTILE_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Right/7.png", .id = .PROJECTILE_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Right/8.png", .id = .PROJECTILE_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Right/9.png", .id = .PROJECTILE_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Right/10.png", .id = .PROJECTILE_TEST_FLYING_RIGHT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Left/1.png", .id = .PROJECTILE_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Left/2.png", .id = .PROJECTILE_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Left/3.png", .id = .PROJECTILE_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Left/4.png", .id = .PROJECTILE_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Left/5.png", .id = .PROJECTILE_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Left/6.png", .id = .PROJECTILE_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Left/7.png", .id = .PROJECTILE_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Left/8.png", .id = .PROJECTILE_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Left/9.png", .id = .PROJECTILE_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Left/10.png", .id = .PROJECTILE_TEST_FLYING_LEFT },
    .{ .path = "assets/visual/Projectile/Test/Flying_Up/1.png", .id = .PROJECTILE_TEST_FLYING_UP },
    .{ .path = "assets/visual/Projectile/Test/Flying_Up/2.png", .id = .PROJECTILE_TEST_FLYING_UP },
    .{ .path = "assets/visual/Projectile/Test/Flying_Up/3.png", .id = .PROJECTILE_TEST_FLYING_UP },
    .{ .path = "assets/visual/Projectile/Test/Flying_Up/4.png", .id = .PROJECTILE_TEST_FLYING_UP },
    .{ .path = "assets/visual/Projectile/Test/Flying_Up/5.png", .id = .PROJECTILE_TEST_FLYING_UP },
    .{ .path = "assets/visual/Projectile/Test/Flying_Up/6.png", .id = .PROJECTILE_TEST_FLYING_UP },
    .{ .path = "assets/visual/Projectile/Test/Flying_Up/7.png", .id = .PROJECTILE_TEST_FLYING_UP },
    .{ .path = "assets/visual/Projectile/Test/Flying_Up/8.png", .id = .PROJECTILE_TEST_FLYING_UP },
    .{ .path = "assets/visual/Projectile/Test/Flying_Up/9.png", .id = .PROJECTILE_TEST_FLYING_UP },
    .{ .path = "assets/visual/Projectile/Test/Flying_Up/10.png", .id = .PROJECTILE_TEST_FLYING_UP },
    .{ .path = "assets/visual/Ui/Ammo/Equals4/1.png", .id = .UI_AMMO_EQUALS4 },
    .{ .path = "assets/visual/Ui/Ammo/Equals1/1.png", .id = .UI_AMMO_EQUALS1 },
    .{ .path = "assets/visual/Ui/Ammo/Equals7/1.png", .id = .UI_AMMO_EQUALS7 },
    .{ .path = "assets/visual/Ui/Ammo/Equals2/1.png", .id = .UI_AMMO_EQUALS2 },
    .{ .path = "assets/visual/Ui/Ammo/Equals6/1.png", .id = .UI_AMMO_EQUALS6 },
    .{ .path = "assets/visual/Ui/Ammo/Equals0/1.png", .id = .UI_AMMO_EQUALS0 },
    .{ .path = "assets/visual/Ui/Ammo/Equals3/1.png", .id = .UI_AMMO_EQUALS3 },
    .{ .path = "assets/visual/Ui/Ammo/Equals5/1.png", .id = .UI_AMMO_EQUALS5 },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/1.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/2.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/3.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/4.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/5.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/6.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/7.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/8.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/9.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/10.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/11.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/12.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/NotPlaying/13.png", .id = .UI_PLAYER_NOTPLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/1.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/2.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/3.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/4.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/5.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/6.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/7.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/8.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/9.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/10.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/11.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/12.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Player/Playing/13.png", .id = .UI_PLAYER_PLAYING },
    .{ .path = "assets/visual/Ui/Health/Equals4/1.png", .id = .UI_HEALTH_EQUALS4 },
    .{ .path = "assets/visual/Ui/Health/Equals11/1.png", .id = .UI_HEALTH_EQUALS11 },
    .{ .path = "assets/visual/Ui/Health/Equals1/1.png", .id = .UI_HEALTH_EQUALS1 },
    .{ .path = "assets/visual/Ui/Health/Equals15/1.png", .id = .UI_HEALTH_EQUALS15 },
    .{ .path = "assets/visual/Ui/Health/Equals8/1.png", .id = .UI_HEALTH_EQUALS8 },
    .{ .path = "assets/visual/Ui/Health/Equals14/1.png", .id = .UI_HEALTH_EQUALS14 },
    .{ .path = "assets/visual/Ui/Health/Equals12/1.png", .id = .UI_HEALTH_EQUALS12 },
    .{ .path = "assets/visual/Ui/Health/Equals7/1.png", .id = .UI_HEALTH_EQUALS7 },
    .{ .path = "assets/visual/Ui/Health/Equals2/1.png", .id = .UI_HEALTH_EQUALS2 },
    .{ .path = "assets/visual/Ui/Health/Equals6/1.png", .id = .UI_HEALTH_EQUALS6 },
    .{ .path = "assets/visual/Ui/Health/Equals9/1.png", .id = .UI_HEALTH_EQUALS9 },
    .{ .path = "assets/visual/Ui/Health/Equals10/1.png", .id = .UI_HEALTH_EQUALS10 },
    .{ .path = "assets/visual/Ui/Health/Equals0/1.png", .id = .UI_HEALTH_EQUALS0 },
    .{ .path = "assets/visual/Ui/Health/Equals13/1.png", .id = .UI_HEALTH_EQUALS13 },
    .{ .path = "assets/visual/Ui/Health/Equals3/1.png", .id = .UI_HEALTH_EQUALS3 },
    .{ .path = "assets/visual/Ui/Health/Equals5/1.png", .id = .UI_HEALTH_EQUALS5 },
    .{ .path = "assets/visual/Ui/Paused/Background/2.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/3.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/4.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/5.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/6.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/7.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/8.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/9.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/10.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/11.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/12.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/13.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/14.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Ui/Paused/Background/15.png", .id = .UI_PAUSED_BACKGROUND },
    .{ .path = "assets/visual/Stage/Meteor/Background/1.png", .id = .STAGE_METEOR_BACKGROUND },
    .{ .path = "assets/visual/Stage/Meteor/Thumbnail/1.png", .id = .STAGE_METEOR_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Meteor/Thumbnail/2.png", .id = .STAGE_METEOR_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Meteor/Thumbnail/3.png", .id = .STAGE_METEOR_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Meteor/Thumbnail/4.png", .id = .STAGE_METEOR_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Meteor/Thumbnail/5.png", .id = .STAGE_METEOR_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Meteor/Thumbnail/6.png", .id = .STAGE_METEOR_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Meteor/Thumbnail/7.png", .id = .STAGE_METEOR_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Meteor/Thumbnail/8.png", .id = .STAGE_METEOR_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Meteor/Thumbnail/9.png", .id = .STAGE_METEOR_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Meteor/Thumbnail/10.png", .id = .STAGE_METEOR_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Meteor/Platforms/1.png", .id = .STAGE_METEOR_PLATFORMS },
    .{ .path = "assets/visual/Stage/Meteor/Floor/1.png", .id = .STAGE_METEOR_FLOOR },
    .{ .path = "assets/visual/Stage/Test00/Background/1.png", .id = .STAGE_TEST00_BACKGROUND },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/1.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/2.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/3.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/4.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/5.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/6.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/7.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/8.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/9.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/10.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/11.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/12.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/13.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/14.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/15.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Thumbnail/16.png", .id = .STAGE_TEST00_THUMBNAIL },
    .{ .path = "assets/visual/Stage/Test00/Platforms/1.png", .id = .STAGE_TEST00_PLATFORMS },
    .{ .path = "assets/visual/Menu/Waiting/ForInput/1.png", .id = .MENU_WAITING_FORINPUT },
    .{ .path = "assets/visual/Menu/Stage/Selected/1.png", .id = .MENU_STAGE_SELECTED },
    .{ .path = "assets/visual/Menu/Stage/Selected/2.png", .id = .MENU_STAGE_SELECTED },
    .{ .path = "assets/visual/Menu/Stage/Selected/3.png", .id = .MENU_STAGE_SELECTED },
    .{ .path = "assets/visual/Menu/Stage/Selected/4.png", .id = .MENU_STAGE_SELECTED },
    .{ .path = "assets/visual/Menu/Stage/Selected/5.png", .id = .MENU_STAGE_SELECTED },
    .{ .path = "assets/visual/Menu/Stage/Selected/6.png", .id = .MENU_STAGE_SELECTED },
    .{ .path = "assets/visual/Menu/Stage/Selected/7.png", .id = .MENU_STAGE_SELECTED },
    .{ .path = "assets/visual/Menu/Stage/Selected/8.png", .id = .MENU_STAGE_SELECTED },
    .{ .path = "assets/visual/Menu/Stage/Selected/9.png", .id = .MENU_STAGE_SELECTED },
    .{ .path = "assets/visual/Menu/Stage/Selected/10.png", .id = .MENU_STAGE_SELECTED },
    .{ .path = "assets/visual/Menu/Stage/Selected/11.png", .id = .MENU_STAGE_SELECTED },
    .{ .path = "assets/visual/Menu/Stage/Selected/12.png", .id = .MENU_STAGE_SELECTED },
};

pub const ASSETS_PER_ID: [ID.size()]usize = .{ 5, 6, 12, 5, 5, 12, 5, 12, 12, 5, 5, 5, 6, 12, 5, 5, 12, 5, 12, 12, 5, 5, 1, 10, 10, 10, 10, 1, 1, 1, 1, 1, 1, 1, 1, 13, 13, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 14, 1, 10, 1, 1, 1, 16, 1, 1, 12 };

// Storage for textures to be initialized at runtime.
var character_test_flying_right_textures: [5]Texture = undefined;
var character_test_standing_textures: [6]Texture = undefined;
var character_test_attacking_left_textures: [12]Texture = undefined;
var character_test_flying_left_textures: [5]Texture = undefined;
var character_test_running_right_textures: [5]Texture = undefined;
var character_test_attacking_right_textures: [12]Texture = undefined;
var character_test_running_left_textures: [5]Texture = undefined;
var character_test_attacking_down_textures: [12]Texture = undefined;
var character_test_attacking_up_textures: [12]Texture = undefined;
var character_test_flying_neutral_textures: [5]Texture = undefined;
var character_test_jumping_textures: [5]Texture = undefined;
var character_wurmple_flying_right_textures: [5]Texture = undefined;
var character_wurmple_standing_textures: [6]Texture = undefined;
var character_wurmple_attacking_left_textures: [12]Texture = undefined;
var character_wurmple_flying_left_textures: [5]Texture = undefined;
var character_wurmple_running_right_textures: [5]Texture = undefined;
var character_wurmple_attacking_right_textures: [12]Texture = undefined;
var character_wurmple_running_left_textures: [5]Texture = undefined;
var character_wurmple_attacking_down_textures: [12]Texture = undefined;
var character_wurmple_attacking_up_textures: [12]Texture = undefined;
var character_wurmple_flying_neutral_textures: [5]Texture = undefined;
var character_wurmple_jumping_textures: [5]Texture = undefined;
var dont_load_texture_textures: [1]Texture = undefined;
var projectile_test_flying_down_textures: [10]Texture = undefined;
var projectile_test_flying_right_textures: [10]Texture = undefined;
var projectile_test_flying_left_textures: [10]Texture = undefined;
var projectile_test_flying_up_textures: [10]Texture = undefined;
var ui_ammo_equals4_textures: [1]Texture = undefined;
var ui_ammo_equals1_textures: [1]Texture = undefined;
var ui_ammo_equals7_textures: [1]Texture = undefined;
var ui_ammo_equals2_textures: [1]Texture = undefined;
var ui_ammo_equals6_textures: [1]Texture = undefined;
var ui_ammo_equals0_textures: [1]Texture = undefined;
var ui_ammo_equals3_textures: [1]Texture = undefined;
var ui_ammo_equals5_textures: [1]Texture = undefined;
var ui_player_notplaying_textures: [13]Texture = undefined;
var ui_player_playing_textures: [13]Texture = undefined;
var ui_health_equals4_textures: [1]Texture = undefined;
var ui_health_equals11_textures: [1]Texture = undefined;
var ui_health_equals1_textures: [1]Texture = undefined;
var ui_health_equals15_textures: [1]Texture = undefined;
var ui_health_equals8_textures: [1]Texture = undefined;
var ui_health_equals14_textures: [1]Texture = undefined;
var ui_health_equals12_textures: [1]Texture = undefined;
var ui_health_equals7_textures: [1]Texture = undefined;
var ui_health_equals2_textures: [1]Texture = undefined;
var ui_health_equals6_textures: [1]Texture = undefined;
var ui_health_equals9_textures: [1]Texture = undefined;
var ui_health_equals10_textures: [1]Texture = undefined;
var ui_health_equals0_textures: [1]Texture = undefined;
var ui_health_equals13_textures: [1]Texture = undefined;
var ui_health_equals3_textures: [1]Texture = undefined;
var ui_health_equals5_textures: [1]Texture = undefined;
var ui_paused_background_textures: [14]Texture = undefined;
var stage_meteor_background_textures: [1]Texture = undefined;
var stage_meteor_thumbnail_textures: [10]Texture = undefined;
var stage_meteor_platforms_textures: [1]Texture = undefined;
var stage_meteor_floor_textures: [1]Texture = undefined;
var stage_test00_background_textures: [1]Texture = undefined;
var stage_test00_thumbnail_textures: [16]Texture = undefined;
var stage_test00_platforms_textures: [1]Texture = undefined;
var menu_waiting_forinput_textures: [1]Texture = undefined;
var menu_stage_selected_textures: [12]Texture = undefined;

pub var texture_slices: [ID.size()][]Texture = .{
    &character_test_flying_right_textures,
    &character_test_standing_textures,
    &character_test_attacking_left_textures,
    &character_test_flying_left_textures,
    &character_test_running_right_textures,
    &character_test_attacking_right_textures,
    &character_test_running_left_textures,
    &character_test_attacking_down_textures,
    &character_test_attacking_up_textures,
    &character_test_flying_neutral_textures,
    &character_test_jumping_textures,
    &character_wurmple_flying_right_textures,
    &character_wurmple_standing_textures,
    &character_wurmple_attacking_left_textures,
    &character_wurmple_flying_left_textures,
    &character_wurmple_running_right_textures,
    &character_wurmple_attacking_right_textures,
    &character_wurmple_running_left_textures,
    &character_wurmple_attacking_down_textures,
    &character_wurmple_attacking_up_textures,
    &character_wurmple_flying_neutral_textures,
    &character_wurmple_jumping_textures,
    &dont_load_texture_textures,
    &projectile_test_flying_down_textures,
    &projectile_test_flying_right_textures,
    &projectile_test_flying_left_textures,
    &projectile_test_flying_up_textures,
    &ui_ammo_equals4_textures,
    &ui_ammo_equals1_textures,
    &ui_ammo_equals7_textures,
    &ui_ammo_equals2_textures,
    &ui_ammo_equals6_textures,
    &ui_ammo_equals0_textures,
    &ui_ammo_equals3_textures,
    &ui_ammo_equals5_textures,
    &ui_player_notplaying_textures,
    &ui_player_playing_textures,
    &ui_health_equals4_textures,
    &ui_health_equals11_textures,
    &ui_health_equals1_textures,
    &ui_health_equals15_textures,
    &ui_health_equals8_textures,
    &ui_health_equals14_textures,
    &ui_health_equals12_textures,
    &ui_health_equals7_textures,
    &ui_health_equals2_textures,
    &ui_health_equals6_textures,
    &ui_health_equals9_textures,
    &ui_health_equals10_textures,
    &ui_health_equals0_textures,
    &ui_health_equals13_textures,
    &ui_health_equals3_textures,
    &ui_health_equals5_textures,
    &ui_paused_background_textures,
    &stage_meteor_background_textures,
    &stage_meteor_thumbnail_textures,
    &stage_meteor_platforms_textures,
    &stage_meteor_floor_textures,
    &stage_test00_background_textures,
    &stage_test00_thumbnail_textures,
    &stage_test00_platforms_textures,
    &menu_waiting_forinput_textures,
    &menu_stage_selected_textures,
};
